/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms.index'
import { Route as AlgorithmsSlugRouteImport } from './routes/algorithms.$slug'
import { Route as ClassificationIndexRouteImport } from './routes/classification.index'
import { Route as ClassificationSlugRouteImport } from './routes/classification.$slug'
import { Route as EvaluationIndexRouteImport } from './routes/evaluation.index'
import { Route as EvaluationSlugRouteImport } from './routes/evaluation.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSlugRoute = AlgorithmsSlugRouteImport.update({
  id: '/algorithms/$slug',
  path: '/algorithms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationIndexRoute = ClassificationIndexRouteImport.update({
  id: '/classification/',
  path: '/classification/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationSlugRoute = ClassificationSlugRouteImport.update({
  id: '/classification/$slug',
  path: '/classification/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationIndexRoute = EvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationSlugRoute = EvaluationSlugRouteImport.update({
  id: '/evaluation/$slug',
  path: '/evaluation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/resources': typeof ResourcesRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/classification/$slug': typeof ClassificationSlugRoute
  '/evaluation/$slug': typeof EvaluationSlugRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/classification/': typeof ClassificationIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/resources': typeof ResourcesRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/classification/$slug': typeof ClassificationSlugRoute
  '/evaluation/$slug': typeof EvaluationSlugRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/classification': typeof ClassificationIndexRoute
  '/evaluation': typeof EvaluationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/resources': typeof ResourcesRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/classification/$slug': typeof ClassificationSlugRoute
  '/evaluation/$slug': typeof EvaluationSlugRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/classification/': typeof ClassificationIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/resources'
    | '/algorithms/$slug'
    | '/classification/$slug'
    | '/evaluation/$slug'
    | '/algorithms/'
    | '/classification/'
    | '/evaluation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/resources'
    | '/algorithms/$slug'
    | '/classification/$slug'
    | '/evaluation/$slug'
    | '/algorithms'
    | '/classification'
    | '/evaluation'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/resources'
    | '/algorithms/$slug'
    | '/classification/$slug'
    | '/evaluation/$slug'
    | '/algorithms/'
    | '/classification/'
    | '/evaluation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ResourcesRoute: typeof ResourcesRoute
  AlgorithmsSlugRoute: typeof AlgorithmsSlugRoute
  ClassificationSlugRoute: typeof ClassificationSlugRoute
  EvaluationSlugRoute: typeof EvaluationSlugRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  ClassificationIndexRoute: typeof ClassificationIndexRoute
  EvaluationIndexRoute: typeof EvaluationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$slug': {
      id: '/algorithms/$slug'
      path: '/algorithms/$slug'
      fullPath: '/algorithms/$slug'
      preLoaderRoute: typeof AlgorithmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification/': {
      id: '/classification/'
      path: '/classification'
      fullPath: '/classification/'
      preLoaderRoute: typeof ClassificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification/$slug': {
      id: '/classification/$slug'
      path: '/classification/$slug'
      fullPath: '/classification/$slug'
      preLoaderRoute: typeof ClassificationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$slug': {
      id: '/evaluation/$slug'
      path: '/evaluation/$slug'
      fullPath: '/evaluation/$slug'
      preLoaderRoute: typeof EvaluationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ResourcesRoute: ResourcesRoute,
  AlgorithmsSlugRoute: AlgorithmsSlugRoute,
  ClassificationSlugRoute: ClassificationSlugRoute,
  EvaluationSlugRoute: EvaluationSlugRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  ClassificationIndexRoute: ClassificationIndexRoute,
  EvaluationIndexRoute: EvaluationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
